# -*- eval: (remove-hook 'before-save-hook 'org-encrypt-entries t); eval: (auto-save-mode 0); -*-
#+TITLE: Configuration
#+AUTHOR: Richard Sent
#+PROPERTY: header-args :results silent :tangle yes :mkdirp yes

This is a comprehensive configuration file for my system. 

* TODO Migrate init.org to here

As part of this I need to modify ~my/tangle-hook~ .

* Warning!

When using noweb, be /very/ careful to be consistent with function
names. If I make a mistake (i.e. using ~src/~ for the name and ~src-~
in the call), ~my/tangle-init~ will fail silently for the rest of the session.

* Base

This heading organizes some basic configurations and prepares various
files. For instance, I have a =setup.sh= script that (ideally)
configures everything and only needs to be run once. We need to make
sure this file is executable.

#+begin_src shell :tangle ~/setup.sh :shebang #!/usr/bin/env bash
#+end_src

I also have a =daemon.sh= file that creates any necessary background
daemons.

#+begin_src shell :tangle ~/daemon.sh :shebang #!/usr/bin/env bash
#+end_src

** Logging

=setup.sh= and any daemons I create should log to this file. Note that
this returns ~" "~ around  the object if you use noweb. As such, I use
~${HOME}/~ instead of ~~/~ as =bash= will complain otherwise if you
try to use it during redirection.

#+NAME: src/config-log-file
#+begin_src emacs-lisp
  "${HOME}/.log.txt"
#+end_src

* Sway

* Bash

** .bashrc

An incomplete =.bashrc= file. I plan on breaking it up across the
config file.

#+begin_src shell :tangle ~/.bashrc
  # /etc/skel/.bashrc
  #
  # This file is sourced by all *interactive* bash shells on startup,
  # including some apparently interactive shells such as scp and rcp
  # that can't tolerate any output.  So make sure this doesn't display
  # anything or bad things will happen !

  export PATH=~/bin:$PATH

  # Test for an interactive shell.  There is no need to set anything
  # past this point for scp and rcp, and it's important to refrain from
  # outputting anything in those cases.
  if [[ $- != *i* ]] ; then
      # Shell is non-interactive.  Be done now!
      return
  fi

  # Put your fun stuff here.
  alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

  # Color output from less
  export LESS_TERMCAP_mb=$'\e[1;32m'
  export LESS_TERMCAP_md=$'\e[1;32m'
  export LESS_TERMCAP_me=$'\e[0m'
  export LESS_TERMCAP_se=$'\e[0m'
  export LESS_TERMCAP_so=$'\e[01;33m'
  export LESS_TERMCAP_ue=$'\e[0m'
  export LESS_TERMCAP_us=$'\e[1;4;31m'

  # Rbenv setup, trying new method to only run if rbenv is installed
  # "$(rbenv init -)"
  if type rbenv >/dev/null 2>&1
  then
      $(rbenv init -)
  fi

  # Use ssh-agent to temporarily store passphrases in RAM
  if ! pgrep -u "$USER" ssh-agent > /dev/null; then
      ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
  fi
  if [[ ! "$SSH_AUTH_SOCK" ]]; then
      source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
  fi

  # Colored diffs and colored cats (meow)
  alias cdiff=colordiff
  alias ccat=bat

  export EDITOR=$'jove'
#+end_src
 
* Encrypted							      :crypt:

-----BEGIN PGP MESSAGE-----

hQIMA341lovNpziwARAAslIvuMqJP4aaBnIoiDmUeCs9KkEV7qmQJUyzJ8xdbDWA
sItFju2rmD3qDluBjPcOHjnfvBue8FfifkDcjH1bfpF2uZquYooAS0v6DERUXLSi
e8+0hJ5OXzZkfkS6BrQf3gIBH9Nby/mIooEdLCioO0UObRm8/7V4GKDMgEMP+bmo
thz2uL+HW1y79+se9fBSp77qdCRJgDqNdHPQ1mpmH6oXLv447hBDMUaf+EZUa1qX
70r6j/57VmpxgjUUXlIMGlErN1B57OEi04q11D6ojn7xM/mxlKp5PVfKF6DAuKy5
QWFS0YjOanpqFq8oySjgpWJAstL+97Ip1GKMPCaRP9EtJLGJH8zgBP4eI6Dqi8kU
yUg4/YE0RIWsdCSPkNGtqdEZNpS4+fmiiqsysXnXgEnu02zl8zfWmSyj93MddLMA
gdrj3wTqf6Ppr2kffFIqis+BVAShJ4/WDpdm0oML5b0OMyfgMEC6Ro2F7MKRklvw
w5W28yjBTEFdZuSU647ye6QANw74kq17VV/3pdPcyFhqkjF/kLsIFdGLCWb1VsYA
CDSwHfrH0jJNfB/9mZ5BHr3PNFCFePzIZuXjxz3BGx8YNzjrIlZ8cF6pOPuuFhHw
eqReYQMdCmJf9JZ2zncqjf3gINbDR+GM2i1Cl9Gm90A9V+tAIlxO5ZX972WH4ZfS
6gG7GtGvrIhSJZ3o9NI8/13lZfNN9AVFaRlli3Q4vh/UtC5NJRGLFTKHEFls3mto
DBeNqzEM+nwz7uzEOs0RYcn6NgfzGCevcb3SeJ1yOmB/H2/dmTcBkhPapFwVVeXk
cr6Gktkd+z55aVlWZv0JpW4CPWcVWqBx/FU2OY9EFXhjBxQ8LHCE8g93CBQVVRch
qYP3Z3CweVDNaWoHIX+hT57glqCQouf2gsJNifyUtr4Ha9tbV6OBJzA/b2TUmcK+
a7j7DGXCPchLp58IYB7nMlhajl+hrQ6EMStZAvwh6CE0jrRK6rXGUqJqp3z8+Fxp
LtsCkFkJ64Gm+LVCluxipKDiRvWc15aLqKBh7eQaaH/nWX9b2ngylFNrkJ2IINPk
lkHr9siJEAfx9UGsG96U2JvjzOf/OlvIiJfDzUhZOJpGKbRt5lxY7vbbr9W/v3AQ
UNzbnAPNurpsFUq0ma73BkxaND9nNKBARGG9LoS9h/Pa/PI7F023kuWbdg9aP5RD
EqPqPiPTrqI+YFmd5rAVB1dvIfdesPk6c72q7peY/FG9p/r0RGRteJ4MvwUTZcGU
VSB4+oTugpYuIS2iOTRxh6hrjgN7A4JK9FTUkfd708L1YQgutlkbS9auVFQ6iFbM
7RFZOXvRHPAVebFRgFJIvPTY2SA09LlaiHD2m90DktmY1g+iW1gCdbcFpxuLA8qR
CqaJ5Ynfy6JojnQHEtq+ZzOUXl6n4/3G0XXmOpQm4oDMC3mEd0nlVHc4Q7Dfu5qD
Ju5EqYPg6l/JzfOLfkINj4e8X04UNuNR0cxEU2OeJ4+WB9b9KrZ4p3NV0zqzHg9o
eDfBTt+KU4pMR2cwFE9JZNiaKQ/xMXtzcdOfIBG3QUG/7ak//gQ9U9rm+2WC1ymc
QVKG6Hoxp1y+z0pwvyhDgHhtY0mzRFUbWWQ4se/ly/i8jQ5nyhdMoOT/7u+bm9xm
x/n75m4up7jjhJ9Va93enBhZaBWbG9mwvj0GDwP/Q6VL1kKMHj7veXIJoswA0YGF
Q/4prPjnPNnBE9Kp2qFoplPbn7hKEuNkPBQts10W6ueiHNYvESVf7eUsJFz+V9Xh
+oMadwCEwsmcp5RDBII5XVL23auzpc7xXFj6v/TzvbUzvSelLXJWdW6m3ZDOjymm
qwNMKE+hUVh688dphPP6zLx1CTTX/xbl1YORBJbH8E0Ti3F31JvRiGVJnUUv1xKs
DLqiBIHuzNg424w0/rWZH75m0KjGByrJS/I6H0byvVJZ09N4BTNQClOjvpx/a2Cv
ee7DBP1X/Xz7LKmCYJCGtLqsTYmVUNjfun85jV+ma6kNgmxBcOPbCieVT86Rp2BL
KvVTqoOkJtqa8buy+V+7rHK6mGQ4sEIZ/lnJiY/a8jdQDbGH4D1LJNzVAgc0rLDW
aEf7hst88Qc87IrS5x03UcEjaOsVxc+bULqd5hxVwd2Mbr3SzNQ3gQxd+FlRQKsc
7viSexLIZZDg/5fJOgwzmES1vZB+NRaWmMhthXUi9Ez4whrW7DMQWtz+7KPRN7kV
JPgFmINk/Md3kZHTWjmBJJ33rrpOey4wsCiCQ2ejieFZkfpSFIB9FCOA+XwrWPzj
7rJLxTWP6cmSFFTW
=CGXy
-----END PGP MESSAGE-----
