# -*- eval: (remove-hook 'before-save-hook 'org-encrypt-entries t); eval: (auto-save-mode 0); -*-
#+TITLE: Configuration
#+AUTHOR: Richard Sent
#+PROPERTY: header-args :results silent :tangle yes :mkdirp yes

This is a comprehensive configuration file for my system. 

* TODO Migrate init.org to here

As part of this I need to modify ~my/tangle-hook~ .

* Warning!

When using noweb, be /very/ careful to be consistent with function
names. If I make a mistake (i.e. using ~src/~ for the name and ~src-~
in the call), ~my/tangle-init~ will fail silently for the rest of the session.

* Base

This heading organizes some basic configurations and prepares various
files. For instance, I have a =setup.sh= script that (ideally)
configures everything and only needs to be run once. We need to make
sure this file is executable.

#+begin_src shell :tangle ~/setup.sh :shebang #!/usr/bin/env bash
#+end_src

I also have a =daemon.sh= file that creates any necessary background
daemons.

#+begin_src shell :tangle ~/daemon.sh :shebang #!/usr/bin/env bash
#+end_src

** Logging

=setup.sh= and any daemons I create should log to this file. Note that
this returns ~" "~ around  the object if you use noweb. As such, I use
~${HOME}/~ instead of ~~/~ as =bash= will complain otherwise if you
try to use it during redirection.

#+NAME: src/config-log-file
#+begin_src emacs-lisp
  "${HOME}/.log.txt"
#+end_src

* Sway

* Bash

** .bashrc

An incomplete =.bashrc= file. I plan on breaking it up across the
config file.

#+begin_src shell :tangle ~/.bashrc
  # /etc/skel/.bashrc
  #
  # This file is sourced by all *interactive* bash shells on startup,
  # including some apparently interactive shells such as scp and rcp
  # that can't tolerate any output.  So make sure this doesn't display
  # anything or bad things will happen !

  export PATH=~/bin:$PATH

  # Test for an interactive shell.  There is no need to set anything
  # past this point for scp and rcp, and it's important to refrain from
  # outputting anything in those cases.
  if [[ $- != *i* ]] ; then
      # Shell is non-interactive.  Be done now!
      return
  fi

  # Put your fun stuff here.
  alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

  # Color output from less
  export LESS_TERMCAP_mb=$'\e[1;32m'
  export LESS_TERMCAP_md=$'\e[1;32m'
  export LESS_TERMCAP_me=$'\e[0m'
  export LESS_TERMCAP_se=$'\e[0m'
  export LESS_TERMCAP_so=$'\e[01;33m'
  export LESS_TERMCAP_ue=$'\e[0m'
  export LESS_TERMCAP_us=$'\e[1;4;31m'

  # Rbenv setup, trying new method to only run if rbenv is installed
  # "$(rbenv init -)"
  if type rbenv >/dev/null 2>&1
  then
      $(rbenv init -)
  fi

  # Use ssh-agent to temporarily store passphrases in RAM
  if ! pgrep -u "$USER" ssh-agent > /dev/null; then
      ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
  fi
  if [[ ! "$SSH_AUTH_SOCK" ]]; then
      source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
  fi

  # Colored diffs and colored cats (meow)
  alias cdiff=colordiff
  alias ccat=bat

  export EDITOR=$'jove'
#+end_src
 
* Encrypted							      :crypt:

-----BEGIN PGP MESSAGE-----

hQIMA341lovNpziwAQ/+Oxn0R2HMj9ZXcyA4IJ20eeI+cgiaVQW/YCwDIAA0+67w
+XMwxQtzibdYB7nFR6mp8L3GP7Vy4sSviwOr7wUIA1ACNVwfivLgVzp6R1cCMFG8
7tA/1U6TUOaCZatTGvQP/nQrzClFGGbvpYbGtJ/38w/FaUIZzF6HIdNdmNtHI9/c
ugQmqVOSAMsf2JM+oblMV1aMyoM4fZvX3vuYdBYYTGpzV9g4Y7BfXv6PHuNMZYsZ
0WSYiSYFL+34l5zPK6t6XwNfC1pN+s5Yy09TrzJZqsDFCqGMY7oEriS54/4hU9aR
BGxWgC305KrZCx0ajiPe1W6rBENSeAqg1ypOLmr/KhfinU0EIvXytLWoeCvsS+fX
77QSHDv6kTfMZe9Ar0I00QxdPh/8/hEBZUnqCsCPc4gko/QR2eADPu+r5+uAQ/PZ
GeJfIk0Hc5OgIP840fTfZ6jJ7KHbmBtuwjCkRpxS3CXW5OeczuIQRfNXSpYZsuoy
uMJNdd87PhTLvAPeBK9TV0V2W9vcbMxsUOvdM082kbxwD6+PgYe4I+ngTrmMYoIw
ksYqK+R70N0Uq7eroe92sy59ruIM0EaemQpnjZHReIil++3NaZd5TfYjkH2lqHZH
OxkbwIFyg8UUdO80PU7FiMmFinlbBzP9+tZLgSKYp4106pYmVJVuse9yylR8vYzS
6gGrvXYaZfVLnlH4uACpvipLb+Kq+At8/ayudarYfApqFwjcPNZkkWKF86eQY1uP
Tg3styvij79RfifBCDrxXrEHN6yiUZTV4FyB1Mpy3flXwso0lgsBJxWRWyjnQbJz
ACEKFeTfxbuiLlkf74wlskuCdM7zKM6esI6uJ3aXSJ9J30jgIRcYrAu/0bADJu5q
DTU981ZAT0G55h682Fc+ZUj1YR6sqhsVzLu9n1JJwKvN2nmLzOF8gNfPzzaHRCpJ
PjeeCwv7hW+z/gmV563aoQJHTTfadnz8wj2f0IAAtVx744aOaTrPMmUjFcvOhcvE
LHqhs2swFYRJC92u8Ejv3fTwpKVl1JN7YlRUfgLlSE6ezIGZR054I+MCQut0ih5U
jnFw1Yv/ASj0yBBQFkWW0Aa6NWePYL/FfIlNjkVhHC8jtscUyDwudX7m396J48na
gXpspJV7Dz7N9kyTOh4tyxKSYaQYK5xqvQWykBQjBjjfEHE/igA8XHDcsf+XO8/J
J5BcWZQYtB85iKnUfMoUmqzFigu1DLa+0VGF52oUXMeWdLjQQkE+B4S85iT9sg6b
PKvbZD1L6Xge6hYfkg9D7ZuUyanD/ud9TK7pGZCAVyi7ZeeNv0g7rP2EErjfLn81
R0YlloMP5Ap8jzsdMeJYaZTvFCOEK+CtZQuQSlbfu1Dq1luP6SF8DVV+UIEZIBcD
1yDm8IRUZ1zG4PuVUytwe9by+box1MI+RJYXEZWOqMfQy9jBpBmY8SH79ubywBkq
kFAgbGa+90xoKRUCwABvGZvpK4g9j4yxAavkG38cr6dWc9wE+wKk3ZbNjXCOopjZ
AFuRtFpkWenyLn8i1xK2dCqFJGJL0sQ/p8wv5CIXIbgK60Mui+aNJvtQvGiLkJDd
IGep7jp3Tg8tcBMmkufW+JsMUD3e4LKnkKwJ+ttMC1Sg9oO9E8K8ThFCD3VNIPQq
JgP5JCZE0PaFDElIQkmb+fOZWogA+2HlzAQ9aa+8CuNYYzExnNJxm4Vx8y5jJgj4
+qJTk/qtRuY7kwhTHDrnPhvI4Kdo5RLVmwfglTtembW7Yht0b2UoFCE5PPobcWdO
AUA1Cx1eaQ6cYeUrIB42pN/cJH6RVTgh8SpSrx3g7RblaTLSYzG0bg2fdOivKcgW
C7gr4fNciEcqfiYpQOrnE0V++RIQgn1sttCmrcbgtkAL/r3AwCWaZtQEsNPxEPw6
YGYoLj0QmDqsrwZbcVbDrUoQP/40zT4rB3vrCcbHk+226CNGMn2tGnx81mNk3Yuv
07qSVLc7CL66GMtvDvtEIjT5mqDFssOpAI9UVz3HZL/QkhVmDahuEPlSB5gE+V3Q
2MuoH/uPYXtBfPVwRvMjioPAUGLWQO/7UzbDiLr/mOAyjO7oqZlwBgjYEL/OecnV
RY89QM9Y2ehHkFnfIEkuVzb6i2VlLedvKKtVNL9VMq4KJuzzkKF8L/7FAdCMafeb
rNXg0yd4ZbUwGqGrhOxtXDuH7HNsEuYi6sNW0/UWYaiHIW+QNR8jD5kuE6Lt51MV
Sl+2Gh00sAhD4d9tPOTw287JVagp38WjcnGAD11alUVgJ2Wm/vMCm5m65sBDly9R
FNXuow2Gs6yNrBg658vgrdazlvCB6j8+SGbk5X1gVU19SztD6yKowxez33r5OxOV
FenC1uv6mYF/IeCYKZZmOPGvlNBL7nTNVghiM0xRVsHUCipOkdsU7W+Ib5dkXaRx
gIuo
=PWoP
-----END PGP MESSAGE-----
